= Draft-Using optional arguments in the MATLAB Java interface
:published_at: 2017-01-25
:hp-tags: MATLAB, Java
:imagesdir: ../images
:source-highlighter: none

++++
<link rel="stylesheet" href="https://cdn.rawgit.com/ennerf/ennerf.github.io/master/resources/highlight.js/9.9.0/styles/matlab.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/languages/matlab.min.js"></script>
<script>hljs.initHighlightingOnLoad()</script>
++++

APIs for MATLAB that were implemented in other languages often don't look like native MATLAB interfaces. We looked at providing a seamless interface that looks like native code. 

Adding dynamic parsing resulted in far fewer support requests caused by confusing behavior. Below we show some options for implementing this.

== Motivation

After several iterations on our MATLAB APIs we became somewhat frustrated because despite significant efforts, the APIs never felt quite like native MATLAB code. The main reason for this was that we limited ourselves to fixed numbers of arguments to simplify the implementation. This worked well for simple use cases, but we kept running into advanced use cases that resulted in confusing behavior or ugly syntax. 

Consider the following (real) example for controlling robot actuators: The majority of users wants to only send position/velocity/torque commands to each joint. However, some expert users would additionally like to set corresponding gains (https://en.wikipedia.org/wiki/Gain_scheduling[gain scheduling]) as well as LED colors for synchronization or debugging with video data from a high-speed camera.

With fixed argument calls this could typically be approached in a few different ways, e.g., as separate method calls, as transactions, or with empty arguments.

[source,matlab]
----
% (1) Separate method calls
sendCommand(cmd);
sendLed(led);
sendGains(gains);

% (2) Transactions
startMessage();
addCommand(cmd);
addLed(led);
addGains(led);
sendMessage();

% (3) Empty arguments
sendMessage(cmd, [], led);
----

All of these options come with drawbacks. (1) divides commands up into three different messages that may not get there at the same time, (2) adds boiler plate code and complicates the common case, and (3) results in code that is difficult to read and write. In reality this gets much worse since there are more than 20 other parameters that users may want to set, e.g., _safety limits_,  _reset flags_, _name/id_, or _calibration commands_. 

Some groups approached similar problems by combining gains and commands into a single struct, but in our case this became overwhelming (>60 fields) and messed with autocomplete in cases like 'position' vs. 'positionKp'. 

At the end of the day, none of these options are particularly satisfying. It'd be much more appropriate to map optional functionality to actual optional parameters. MATLAB already established a way to do this by splitting arguments into _required_, _optional_, and _key/value parameter_ arguments. The example below shows some different ways to call the plot command.

[source,matlab]
----
% various ways to call plot
plot(x,y);
plot(x,y,'--rs');
plot(x,y,'--rs', ...
    'LineWidth', 2,...
    'MarkerEdgeColor', 'k', ...
    'MarkerFaceColor', 'g', ...
    'MarkerSize', 10)
----

The problem stated earlier could be solved in the same way, e.g.,

[source,matlab]
----
% common use case
sendMessage(cmd);

% advanced use case
sendMessage(cmd, 'led', led, 'gains', gains);
----

This way the syntax matches built-in functions and is much more intuitive for MATLAB users. Additionally, the string arguments make the code much more readable because the argument order is immediately obvious.

Unfortunately, this does not work with a fixed argument approach and is more difficult to implement due to additional parsing and input validation.

== InputParser

The simplest way to do parse arguments would be to use MATLAB's built-in https://www.mathworks.com/help/matlab/ref/inputparser-class.html[inputParser].  It supports the different argument types as well as default values and input validation. The rules are as follows,

* *Required* arguments come first and are parsed in the same order they were defined in.
* *Optional* arguments are expected after all required arguments are satisfied. An optional argument is set if its validator returns true. If the validator returns false, the parser will try the validator of the next optional argument.
* *Parameters* are parsed last and consist of a string-key and a single corresponding value argument. They can be set in any order.

Creating an inputparser looks as shown in the code below.

[source,matlab]
----
% set defaults
defaultHeight = 1;
defaultUnits = 'inches';
defaultShape = 'rectangle';
expectedShapes = {'square','rectangle','parallelogram'};

% add possible arguments
p = inputParser;
p.addRequired('width',@isnumeric);
p.addOptional('height',defaultHeight,@isnumeric);
p.addParameter('units',defaultUnits);
p.addParameter('shape',defaultShape, @(x) any(validatestring(x,expectedShapes)));

% parse user input
p.parse(varargin{:});
a = p.Results.width .* p.Results.height;
----

Once the arguments are parsed, the result can be forwarded to an internal method that is implemented with fixed arguments.

[source,matlab]
----
function [out] = myMethod(this, varargin)
    % parse user input
    p = createInputParser();
    p.parse(varargin{:});
    
    % call backing implementation
    r = p.Results;
    out = myMethod(this.javaObj, r.width, r. height, r.units, r.shape);
end
----

Overall this worked well for some cases, but we quickly ran into some limitations such as,

* Automated API tests now have a dependency on MATLAB
* It can be difficult to check whether a user actually set a value, e.g., common default values like nan or empty may sometimes be valid inputs
* Validation can become very complex
* Error messages become less useful for cases with non-trivial validation
* There are methods with >20 parameters, at which point this approach becomes unmaintainable and actually degrades performance.

== Custom InputParser

Instead of doing the parsing on the MATLAB side of the API, we decided to implement equivalent parsing functionality that lives entirely behind the Java barrier. 

=== varargin

In our attempt to replicate this functionality in Java, we immediately faced the first issue. The Java language has an equivalent of MATLAB's _varargin_ called _varargs_, which can accept zero or more arguments of the given type.

[source,Java]
----
public void varargsMethod(Object... args){}
----

Unfortunately MATLAB does not support this correctly and interprets _Object..._ the same as the non-varargs _Object_ and expects exactly one argument. However, the same functionality can still be supported by creating method overloads that gather input arguments.

[source,Java]
----
public final class JavaClass {

    public Object myMethod() {
        return myMethod0();
    }

    public Object myMethod(Object o0) {
        return myMethod0(o0);
    }

    public Object myMethod(Object o0, Object o1) {
        return myMethod0(o0, o1);
    }

    public Object myMethod(Object o0, Object o1, Object o2) {
        return myMethod0(o0, o1, o2);
    }

    public Object myMethod(Object o0, Object o1, Object o2, Object o3) {
        return myMethod0(o0, o1, o2, o3);
    }

    public Object myMethod(Object o0, Object o1, Object o2, Object o3, Object o4) {
        return myMethod0(o0, o1, o2, o3, o4);
    }

    private Object myMethod0(Object... args) {
        // parse arguments and implement functionality
        MyMethodParser p = MyMethodParser.parse(args);
        return args;
    }
    
}
----

Unfortunately, this quickly becomes unmaintainable for large APIs that have many methods where each can have many arguments. As a result we developed annotation processors that can automatically generate most of the boiler plate code necessary for interfacing with MATLAB.

[source,Java]
----
@MatlabMethod(maxArgs = 20)
public Object myMethod0(Object... args){
    // ...
}
----

As of this point we have not open sourced these annotation processors, but we may do so in the future.

////
* We need to support arbitrary number of arguments, but Java's varargs _Object..._ does not work

In Java _Object..._ means zero or more argument of the given type. MATLAB unfortunately interprets this equivalent to _Object_ and expects exactly one argument. We ended up working around this limitation by creating many overloads for every method.
////


== Type Conversions

////

The second issue we encountered was that 

* Parameters are all _Object_, so we loose any type conversion and need to support all possible combinations

The MATLAB-Java interface usually handles type conversion automatically to match the target method. This means that a Java method that expects a double will always see a double, no matter whether the actual input type used to be single or int16. However, if the method accepts _Object_, MATLAB converts to the closest matching data type, e.g., _single_ and _int8_ convert to _float_ and _byte_ respectively. 

////

The most extreme example we've so far encountered was a method to set the led color of our components. The goal was to support all representations of colors that MATLAB users are familiar with, and to allow convenient syntax for setting multiple colors at once.

Thus, for a single module it needs to support the following representations:

* Strings: 'red', 'blue', 'green', ...
* Shorthand: 'r', 'b', 'g', ...
* Array: [1 0 0], [0 1 0], [0 0 1], ...

Additionally, more than one module may be targeted in a single call, so it also needs to support the corresponding vector/matrix versions. MATLAB numbers can be practically any data type, so the parser needs to support all of the following Java types, as well as provide input validation with proper error checks.

[source,Java]
----
String, String[], 
byte[], short[], int[], long[], float[], double[], 
byte[][], short[][], int[][], long[][], float[][], double[][]
----